name: hypersim
disp_name: hypersim_val_all
dir: /home/a/Desktop/Vision/KTJ/BEFORE/Marigold_main/학위논문_비교실험/PCB-open-2/PCB-open-2.tar
filenames: /home/a/Desktop/Vision/KTJ/BEFORE/Marigold_main/학위논문_비교실험/PCB-open-2/PCB-open-2.txt
